title:         Emacs Perú User Group
description:   Emacs Perú home page

exclude:       [ vendor ]

permalink:     pretty

links:
  - name:      About
    url:       /about/
  - name:      elpa
    url:       /packages/
