title:         Emacs Perú User Group
description:   Emacs Perú home page

exclude:       [ vendor ]

highlighter:   pygments
permalink:     pretty
markdown:      redcarpet
redcarpet:
  extensions:
    - smart

links:
  - name:      About
    url:       /about/
  - name:      elpa
    url:       /packages/
